default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 10) %>

development:
  <<: *default
  database: runa_development

test:
  <<: *default
  database: runa_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
